name: Angular Build

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    name: Build Angular Application
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.15.0

    - name: Install dependencies
      run: npm ci

    - name: Build Angular application
      run: npm run build --configuration=production

  publish-image:
    runs-on: ubuntu-latest
    needs: build
    name: Publish Docker Image
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Build
        run: |
          IMAGE_TAG=wesleycosta/orangotango-app:$(date +'%Y%m%d%H%M%S')
          docker build . --file Dockerfile --tag $IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          
      - name: Docker Push
        run: |
          docker tag $IMAGE_TAG wesleycosta/orangotango-app:latest
          docker push wesleycosta/orangotango-app:latest

