name: Angular Application

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    name: Build Angular Application
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci

    - name: Build Angular application
      run: npm run build -- --prod

  publish-image:
    runs-on: ubuntu-latest
    needs: build
    name: Publish Docker Image
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker image
        run: |
          IMAGE_TAG=${{ secrets.DOCKER_USER }}/orangotango-app:$(date +'%Y%m%d%H%M%S')
          docker buildx build --platform linux/amd64,linux/arm64 --push --tag $IMAGE_TAG .
          docker tag $IMAGE_TAG ${{ secrets.DOCKER_USER }}/orangotango-app:latest
          docker push ${{ secrets.DOCKER_USER }}/orangotango-app:latest
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
